### ISSUE TITLE
error 500 / CORS on post martian trade

### ISSUE THREAD

**Issue by Jarvilito** [Blackpepper/frontend-developer-test#10]
Hi again,

I'm encountering error 500 or CORS error when using POST method with this api /martian/trade

![image](https://user-images.githubusercontent.com/56264673/183129987-54ba5b75-3e9a-48c9-8c19-d47f00bf644f.png)

thank you!

**Comment by alainrussell** [comment]
Hi, can you give me an example of the payload you are sending? We're logging errors that the data is unexpected so I'd like to test with the JSON in your payload. Thanks :)

**Comment by Jarvilito** [comment]
hi tried in just now and it seems like its working. Thanks
