### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by moniqueclariza03** [Blackpepper/frontend-developer-test#2]
Hi again! would like to ask if you guys can elaborate the formula on what the expected data that will be passed on the post service?
Thanks

**Comment by ginaliao** [comment]
Hi Mon, so the `buyFrom` and `sellTo` objects will contain the ID of the 2 traders and _only_ the items they are adding to the trade (the array of objects contains the ID of the item as well as how many they are trading). The associated `itemid` you can get from the `GET Index/List Martian Items` endpoint.

Does that answer your question? Let me know if not :)

**Comment by moniqueclariza03** [comment]
thanks gina for the fast response :) yup im good with it.
