### ISSUE TITLE
503 Status code for Martian Items GET API

### ISSUE THREAD

**Issue by moniqueclariza03** [Blackpepper/frontend-developer-test#4]
![image](https://user-images.githubusercontent.com/11714285/176422941-fa9d45d9-4c63-488f-a916-65114ba803ea.png)

Also checked and tested the API thru insomnia

![image](https://user-images.githubusercontent.com/11714285/176424784-7f9d880b-56e7-4385-8ac7-32ea797394c6.png)

**Comment by ginaliao** [comment]
Not sure what happened, but looks to be working at the moment. Let me know if you have any more issues.

**Comment by moniqueclariza03** [comment]
api works fine now
