### ISSUE TITLE
502 Status code Martian List GET API

### ISSUE THREAD

**Issue by moniqueclariza03** [Blackpepper/frontend-developer-test#5]
![image](https://user-images.githubusercontent.com/11714285/176431263-0dcee8dd-2384-4573-9741-be2e3c3eb373.png)
![image](https://user-images.githubusercontent.com/11714285/176430965-d6dfccb6-56bc-4369-a134-417faa551f0b.png)

**Comment by ginaliao** [comment]
Same with this one, looks to be working now but let me know if not.

**Comment by moniqueclariza03** [comment]
works fine now.
