### ISSUE TITLE
CORS ERROR

### ISSUE THREAD

**Issue by Jarvilito** [Blackpepper/frontend-developer-test#9]
Hi im currently encountering cors error on accessing API 
![image](https://user-images.githubusercontent.com/96861142/182081724-624d02f4-3e12-4727-b8dd-415de7b9f92b.png)
![image](https://user-images.githubusercontent.com/96861142/182081811-1ab98a23-e217-4600-8456-c1fc0dea5086.png)

**Comment by alainrussell** [comment]
Can you check the URL, I think it should be https://www.blackpepper.co.nz/api/martian/items
